//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearTI.NET.Contlib.Samples.FileUploader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DynamicPicturesUploaderHandlerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicPicturesUploaderHandlerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PearTI.NET.Contlib.Samples.FileUploader.Resources.DynamicPicturesUploaderHandlerS" +
                            "trings", typeof(DynamicPicturesUploaderHandlerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file size is too big. Please select a file that not exceed {0} and try again..
        /// </summary>
        public static string FileMaxSizeExceeded {
            get {
                return ResourceManager.GetString("FileMaxSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file size is too small. Please select a file that is bigger than {0} and try again..
        /// </summary>
        public static string FileMinSizeNotReached {
            get {
                return ResourceManager.GetString("FileMinSizeNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload was paused by the user..
        /// </summary>
        public static string FileUploadAbroted {
            get {
                return ResourceManager.GetString("FileUploadAbroted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image height is too big. The image maximum allowed height is {0}..
        /// </summary>
        public static string ImageMaxAllowedHeightExceeded {
            get {
                return ResourceManager.GetString("ImageMaxAllowedHeightExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image width is too big. The image maximum allowed width is {0}..
        /// </summary>
        public static string ImageMaxAllowedWidthExceeded {
            get {
                return ResourceManager.GetString("ImageMaxAllowedWidthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך התמונה שהועלתה קטן מדי. על התמונה להיות לפחות באורך {0} פיקסלים..
        /// </summary>
        public static string ImageMinAllowedHeightNotMet {
            get {
                return ResourceManager.GetString("ImageMinAllowedHeightNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image width is too small. The image minimum allowed width is {0}..
        /// </summary>
        public static string ImageMinAllowedWidthNotMet {
            get {
                return ResourceManager.GetString("ImageMinAllowedWidthNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file type is invalid. The image must be gif, jpeg or png..
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve exceeded your max allowed files to upload. You can upload up to {0} files..
        /// </summary>
        public static string MaximumNumberOfFilesExcceded {
            get {
                return ResourceManager.GetString("MaximumNumberOfFilesExcceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file type is invalid. The image must be gif, jpeg or png..
        /// </summary>
        public static string NotValidImage {
            get {
                return ResourceManager.GetString("NotValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The posted file is too big. Please select smaller file and try again..
        /// </summary>
        public static string PostMaxSizeExceeded {
            get {
                return ResourceManager.GetString("PostMaxSizeExceeded", resourceCulture);
            }
        }
    }
}
