//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearTI.NET.Contlib.UI.Handlers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DynamicPicturesUploaderHandlerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicPicturesUploaderHandlerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNadlan.Web.UI.Handlers.DynamicPicturesUploaderHandlerStrings", typeof(DynamicPicturesUploaderHandlerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גודל הקובץ הנבחר גדול מדיי, אנא בחר קובץ שאינו עולה על {0} ונסה שנית..
        /// </summary>
        internal static string FileMaxSizeExceeded {
            get {
                return ResourceManager.GetString("FileMaxSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ שהועלה קטן מדיי, אנא בחר קובץ הגדול מ-{0} ונסה שנית..
        /// </summary>
        internal static string FileMinSizeNotReached {
            get {
                return ResourceManager.GetString("FileMinSizeNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העלאת הקובץ הופסקה על ידי המשתמש..
        /// </summary>
        internal static string FileUploadAbroted {
            get {
                return ResourceManager.GetString("FileUploadAbroted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך התמונה שהועלה גדול מדיי. על התמונה לא להיות באורך הגבוה מ-{0} פיקסלים..
        /// </summary>
        internal static string ImageMaxAllowedHeightExceeded {
            get {
                return ResourceManager.GetString("ImageMaxAllowedHeightExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רוחב התמונה שהועלה גדול מדיי. על התמונה לא להיות ארוכה מ-{0} פיקסלים..
        /// </summary>
        internal static string ImageMaxAllowedWidthExceeded {
            get {
                return ResourceManager.GetString("ImageMaxAllowedWidthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך התמונה שהועלתה קטן מדי. על התמונה להיות לפחות באורך {0} פיקסלים..
        /// </summary>
        internal static string ImageMinAllowedHeightNotMet {
            get {
                return ResourceManager.GetString("ImageMinAllowedHeightNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רוחב התמונה שהועלתה קטן מדי. על התמונה להיות לפחות ברוחב {0} פיקסלים..
        /// </summary>
        internal static string ImageMinAllowedWidthNotMet {
            get {
                return ResourceManager.GetString("ImageMinAllowedWidthNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ שנבחר אינו קובץ תמונה נבחר, אנא בחר קובץ תמונה מסוג gif, jpg (jpeg) ו-png בלבד..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגעת למחסת הקבצים המוקצת לך. הנך מורשה להעלות עד {0} קבצים..
        /// </summary>
        internal static string MaximumNumberOfFilesExcceded {
            get {
                return ResourceManager.GetString("MaximumNumberOfFilesExcceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ שנבחר אינו קובץ תמונה נבחר, אנא בחר קובץ תמונה מסוג gif, jpg (jpeg) ו-png בלבד..
        /// </summary>
        internal static string NotValidImage {
            get {
                return ResourceManager.GetString("NotValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גודל הקובץ הנבחר גדול מדיי, אנא בחר קובץ בעל נפח קטן יותר ונסה שנית..
        /// </summary>
        internal static string PostMaxSizeExceeded {
            get {
                return ResourceManager.GetString("PostMaxSizeExceeded", resourceCulture);
            }
        }
    }
}
